#!/bin/sh

set -e

case "$1" in
   configure)

		PACKAGE_NAME="lliurex-extra-configs"
		
		# GIMP
		
		DEFAULT_GIMP_CONF="/etc/gimp/2.0/gimprc"
		LLIUREX_GIMP_CONF="/etc/gimp/2.0/gimprc.lliurex"
		DIVERTED_GIMP_CONF="/etc/gimp/2.0/gimprc.diverted"


		if [ -f $DEFAULT_GIMP_CONF ]; then
			if dpkg-divert --package ${PACKAGE_NAME} --add  --rename  --divert ${DIVERTED_GIMP_CONF} ${DEFAULT_GIMP_CONF} ; then
				ln -fs ${LLIUREX_GIMP_CONF} ${DEFAULT_GIMP_CONF} || true
		fi
		
		##
		

   ;;

   abort-upgrade|abort-remove|abort-deconfigure)
   ;;

   *)
       exit 1
   ;;
esac

#DEBHELPER#

exit 0

